name: py-test
on:
  workflow_dispatch:
jobs:
  job0:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    env:
      VERBOSE: 1
      Python3_ROOT_DIR: "c:/hostedtoolcache/windows/python/3.8.10/x64"
      Python3_FIND_STRATEGY: "LOCATION"
      Python3_FIND_REGISTRY: "NEVER"
    steps:
      - uses: actions/checkout@v4
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.23.0"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Python info - bash
        run: |
          python --version
          pip --version
          which python
          which pip
          echo "path: '$PATH'"
          cmake -P "${{ github.workspace }}/snippet.cmake"
      - name: Python info - cmd
        shell: cmd
        run: |
          python --version
          pip --version
          where python
          where pip
          echo "path: '%PATH%'"
          cmake -P "${{ github.workspace }}/snippet.cmake"
      - name: Setup ROS 2 Python venv
        run: |
          echo "path: '$PATH'"
          pip install -U wheel
          pip install vcstool
          echo "path: '$PATH'"
      - name: Python info 2 - bash
        run: |
          python --version
          pip --version
          which python
          which pip
          echo "path: '$PATH'"
          cmake -P "${{ github.workspace }}/snippet.cmake"
      - name: Python info 2 - cmd
        shell: cmd
        run: |
          python --version
          pip --version
          where python
          where pip
          echo "path: '%PATH%'"
          cmake -P "${{ github.workspace }}/snippet.cmake"
