name: py-test
on:
  workflow_dispatch:
jobs:
  job0:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    env:
      VERBOSE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.23.0"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Python info - bash
        run: |
          ls -al /c/hostedtoolcache/windows/python/3.8.10/x64
          echo "---"
          python --version
          pip --version
          echo "---"
          which python
          which pip
          echo "---"
          echo "path: '$PATH'"
          echo "---"
          cmake -P "${{ github.workspace }}/snippet.cmake"
          echo "---"
          cmake \
            --debug-find \
            -DPython3_EXECUTABLE=$(which python) \
            -DPython3_ROOT_DIR="/c/hostedtoolcache/windows/python/3.8.10/x64" \
            -DPython3_FIND_STRATEGY=LOCATION \
            -DPython3_FIND_REGISTRY=NEVER \
            -P "${{ github.workspace }}/snippet.cmake"
      - name: Python info - cmd
        shell: cmd
        run: |
          dir /ah C:/hostedtoolcache/windows/python/3.8.10/x64
          echo ---
          python --version
          pip --version
          echo ---
          where python
          where pip
          echo ---
          echo "path: '%PATH%'"
          echo ---
          cmake -P "${{ github.workspace }}/snippet.cmake"
          echo ---
          cmake ^
            --debug-find ^
            -DPython3_EXECUTABLE=$(which python) ^
            -DPython3_ROOT_DIR="c:/hostedtoolcache/windows/python/3.8.10/x64" ^
            -DPython3_FIND_STRATEGY=LOCATION ^
            -DPython3_FIND_REGISTRY=NEVER ^
            -P "${{ github.workspace }}/snippet.cmake"
      - name: Setup ROS 2 Python venv
        run: |
          echo "path: '$PATH'"
          pip install -U wheel
          pip install vcstool
          echo "path: '$PATH'"
      - name: Python info 2 - bash
        run: |
          ls -al /c/hostedtoolcache/windows/python/3.8.10/x64
          echo "---"
          python --version
          pip --version
          echo "---"
          which python
          which pip
          echo "---"
          echo "path: '$PATH'"
          echo "---"
          cmake -P "${{ github.workspace }}/snippet.cmake"
          echo "---"
          cmake \
            -DPython3_ROOT_DIR="/c/hostedtoolcache/windows/python/3.8.10/x64" \
            -DPython3_FIND_STRATEGY=LOCATION \
            -DPython3_FIND_REGISTRY=NEVER \
            -P "${{ github.workspace }}/snippet.cmake"
      - name: Python info 2 - cmd
        shell: cmd
        run: |
          dir /ah C:/hostedtoolcache/windows/python/3.8.10/x64
          echo ---
          python --version
          pip --version
          echo ---
          where python
          where pip
          echo ---
          echo "path: '%PATH%'"
          echo ---
          cmake -P "${{ github.workspace }}/snippet.cmake"
          echo ---
          cmake ^
            -DPython3_ROOT_DIR="c:/hostedtoolcache/windows/python/3.8.10/x64" ^
            -DPython3_FIND_STRATEGY=LOCATION ^
            -DPython3_FIND_REGISTRY=NEVER ^
            -P "${{ github.workspace }}/snippet.cmake"
